FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app.py .
CMD ["gunicorn", \
     "--certfile=/certs/resource.crt", \
     "--keyfile=/certs/resource.key", \
     "-b", "0.0.0.0:5002", \
     "--workers=2", \
     "app:app"]
